version: 2
env:
  - GO111MODULE=on
before:
  hooks:
    - go generate ./...
    - go mod download
project_name: supervisord-plus
builds:
  - id: static
    env:
      - CGO_ENABLED=1
    binary: supervisord_static
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-linkmode external -extldflags -static"
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    binary: supervisord-plus
    flags:
      - -tags=release
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
        # hooks:
        # post:
        # - chmod +X upx.sh
      # - sh ./upx.sh

archives:
  - id: static
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    allow_different_binary_count: true
# archives:
#   name_template:
#     - "
#   format: tar.gz
#   format_overrides:
#     - goos: windows
#       format: zip
#   wrap_in_directory: true
#   files:
#     - none*

release:
  github:
    owner: couriourc
    name: supervisord-plus
  draft: false
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.ShortCommit}}"
